image: harbor.genchuan.cn/library/node:v20.15.0-alpine-docker-pnpm

stages:
  - build_and_push

variables:
  DOCKER_IMAGE: "docker-iamges"
  HARBOR_USER: "user"
  HARBOR_PASSWORD: "password"
  PIPELINE_TAG: "$CI_COMMIT_BRANCH"
build_and_push:
  stage: build_and_push
  script:
    # 安装依赖并构建
    - pnpm install
    - pnpm run build:$PIPELINE_TAG
    
    # 登录 Docker 仓库
    - echo "登录 Harbor 仓库..."
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD harbor.genchuan.cn
    
    # 构建 Docker 镜像
    - echo "构建 Docker 镜像..."
    - docker build -t $DOCKER_IMAGE:$PIPELINE_TAG .
    
    # 推送 Docker 镜像
    - echo "推送 Docker 镜像..."
    - docker push $DOCKER_IMAGE:$PIPELINE_TAG
  retry:
    max: 2  # 最大重试次数
    when:  # 重试条件
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure