#基础可用的未做任何安全配置
FROM harbor.genchuan.cn/library/nginx:1.25.4-alpine

ENV LANG=en_US.UTF-8
RUN mkdir -p /var/www

COPY dist/ /var/www/dist/

COPY kubernetes/nginx/default.conf /etc/nginx/conf.d/default.conf