server {
    listen 80;
    index index.html index.htm index.php;
    root /var/www/dist;
    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        # rewrite ^.+(?<!js|css|png|map|jpg|gif|jpeg|woff|svg|ttf|eot)$ /index.html break;
    }       
}   

