apiVersion: apps/v1
kind: Deployment
metadata:
  name: yudao-module-smartcity-biz
  namespace: test
  labels:
    app: yudao-module-smartcity-biz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yudao-module-smartcity-biz
  template:
    metadata:
      labels:
        app: yudao-module-smartcity-biz
    spec:
      containers:
      - name: yudao-module-smartcity-biz
        image: harbor.genchuan.cn/sccsgl/yudao-module-smartcity-biz:laster
        imagePullPolicy: Always
        ports:
        - containerPort: 58081

---
apiVersion: v1
kind: Service
metadata:
  name: yudao-module-smartcity-biz
  namespace: test
spec:
  selector:
    app: yudao-module-smartcity-biz
  ports:
    - protocol: TCP
      port: 58081
      targetPort: 58081
  type: NodePort